---
title: Erin Feaser
baseURL: "/"
params:
  layout_style: grid
  palette: black
  header:
    title: Erin Feaser
    logo_img: "/images/erinf_site.png"
    has_nav: true
  footer:
    content: Erin Feaser 2020&copy; All rights reserved.
    links: []
    has_social: true
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
