---
title: Erin Feaser
baseURL: "/"
params:
  layout_style: grid
  palette: black
  header:
    title: Erin Feaser
    logo_img: "/images/name_logo.png"
    has_nav: true
  footer:
    content: "&copy; All rights reserved."
    links:
    - text: Made with Stackbit
      url: https://www.stackbit.com
      new_window: true
    has_social: true
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
